In [5]:
import numpy as np

### Maths

In [8]:
a = [[6, 3], [5, 4]]
b = [[7, 1], [9, 2]]
ar = np.array(a)
br = np.array(b)
ar

array([[6, 3],
       [5, 4]])

In [9]:
br

array([[7, 1],
       [9, 2]])

In [7]:
ar + br

array([[13,  4],
       [14,  6]])

In [10]:
ar - br 

array([[-1,  2],
       [-4,  2]])

In [11]:
ar * br

array([[42,  3],
       [45,  8]])

In [12]:
ar / br

array([[0.85714286, 3.        ],
       [0.55555556, 2.        ]])

In [14]:
# raise power
ar ** 2

array([[36,  9],
       [25, 16]])

In [15]:
# trigonometric fnctions
np.sin(ar)

array([[-0.2794155 ,  0.14112001],
       [-0.95892427, -0.7568025 ]])

In [17]:
# check square root
np.sqrt(ar)

array([[2.44948974, 1.73205081],
       [2.23606798, 2.        ]])