### Re organising arrays

In [1]:
import numpy as np

In [4]:
a1 = np.array([(1, 2, 3), (2, 5, 8)])
a1

array([[1, 2, 3],
       [2, 5, 8]])

In [16]:
# to check shape
a1.shape

(2, 3)

In [17]:
# transposes the data
a1.T

array([[1, 2],
       [2, 5],
       [3, 8]])

In [18]:
b =  a1.reshape((6,1))
b

array([[1],
       [2],
       [3],
       [2],
       [5],
       [8]])

In [19]:
a2 = np.array([(3, 7, 7), (9, 3, 6)])
a2

array([[3, 7, 7],
       [9, 3, 6]])

In [20]:
# to vertically stack data
np.vstack([a1,a2])

array([[1, 2, 3],
       [2, 5, 8],
       [3, 7, 7],
       [9, 3, 6]])

In [21]:
# to horizontally stack data
np.hstack([a1,a2])

array([[1, 2, 3, 3, 7, 7],
       [2, 5, 8, 9, 3, 6]])