### Random numbers


In [2]:
import numpy as np
# random decimal numbers
np.random.rand(3, 4)

array([[0.75012407, 0.84298311, 0.96046108, 0.9873941 ],
       [0.61621759, 0.46882474, 0.07072961, 0.96947916],
       [0.85115385, 0.24690618, 0.63552032, 0.64609555]])

In [5]:
# random integer numbers
np.random.randint(15, size=(3, 3))

array([[ 8,  8,  8],
       [ 4, 11, 12],
       [ 7,  9,  6]])

In [6]:
# random integer numbers between range
np.random.randint(10, 15, size=(3, 3))

array([[11, 10, 10],
       [14, 12, 10],
       [11, 14, 13]])

In [8]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# initialize this array
# 1 1 1 1 1
# 1 0 0 0 1
# 1 0 9 0 1
# 1 0 0 0 1
# 1 1 1 1 1
arr = [[1, 1, 1, 1, 1], [1, 0, 0, 0, 1], [1, 0, 9, 0, 1], [1, 0, 0, 0, 1], [1, 1, 1, 1, 1]]
np.array(arr)

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [21]:
# or we can do it like this
a = np.ones([5, 5])
a
z = np.zeros([3,3])
z[1, 1] = 9
z
a[1:4, 1:4] = z
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])