Accessing/Changes specific elements of rows/columns

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [3]:
# get a specific element
a[1, 5]

13

In [6]:
# get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
# get a specific column
a[:, 2]

array([ 3, 10])

In [8]:
a[0, 3:7]

array([4, 5, 6, 7])

In [11]:
a[1, 6] = 144
a

array([[  1,   2,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12,  13, 144]])

Initialising different types of arrays

In [14]:
# all zero matrix
np.zeros([3, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
# all one metrix
np.ones([4, 2, 2])

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [18]:
# any other number
np.full([2,3],15, dtype='float32')

array([[15., 15., 15.],
       [15., 15., 15.]], dtype=float32)