### Loading Data from A file

In [2]:
import numpy as np

In [4]:
fd = np.genfromtxt('NumPy Data.txt', delimiter=',')

In [5]:
fd

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,   0.],
       [ 11.,  22.,  33.,  44.,  55.,  66.,  77.,  88.,  99.,   0.],
       [111., 222., 333., 444., 555., 666., 777., 888., 999.,   0.]])

### Advanced Indexing

In [6]:
fd > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False,  True,  True,  True,  True,  True,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False]])

In [7]:
fd[fd > 50]

array([ 55.,  66.,  77.,  88.,  99., 111., 222., 333., 444., 555., 666.,
       777., 888., 999.])

In [8]:
np.all(fd > 50, axis=1)

array([False, False, False])

In [10]:
((fd > 50) & (fd < 100))

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False,  True,  True,  True,  True,  True,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [11]:
vg = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15,],[16,17,18,19,20],[21,22,23,24,25]]
ax = np.array(vg)
ax

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
ax[3:, 3:]

array([[19, 20],
       [24, 25]])

In [23]:
ax[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [26]:
ax[2:4, 0:2]

array([[11, 12],
       [16, 17]])